sources:
  - name: s1
    database: hdfc_db
    schema: dev_schema
    tables:
      - name: customers
      - name: orders
      - name: payments
      - name: t_ticket_track
      - name: t_customers
      - name: t_nations
      - name: t_discount
      - name: t_audit
      - name: s_emp
